### ISSUE TITLE
TCK failed after switching to @Deployment(testable=false)

### ISSUE THREAD

**Issue by antoinesd** [smallrye/smallrye-health#31]
During MP Health development, we changed all arquillian deployment to `@Deployment(testable = false)` in PR [135](/eclipse/microprofile-health/pull/135).
Now we fail all TCK test with a 404 error.

This should be investigated before MP Health 2.0 release

**Comment by xstefank** [comment]
As there is essentially no documentation for Arquillian loadable extensions, it took me a while but the problem is that when deployment is not testable services registered with loadable exensions are not fired - https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGenerator.java#L152 and thus our https://github.com/smallrye/smallrye-health/blob/master/tck/src/test/java/io/smallrye/health/SmallRyeHealthArchiveProcessor.java is not being run.

I don't know of any other way how to include any additional classes and resources to the deployment so I think the best way will be to revert testable = false change in the TCK.

cc @rsvoboda

**Comment by Ladicek** [comment]
I agree, but I also think that this is actually caused by SmallRye Health running the MP Health TCK in a very weird environment that isn't representative of anything that would actually be used in real world.

**Comment by xstefank** [comment]
it should be an easy change in arquillian to just remove the condition causing this problem but as we need to have TCK passing because of the coming 2.0 release can we take a look at it afterwards?

**Comment by Ladicek** [comment]
I believe that the logic in Arquillian is intentional. If the deployment isn't "testable", it's not supposed to be modified. That of course assumes that it's deployed to something that can actually run it :-) I went through the POMs and I actually have no idea what Arquillian container we use for running the TCK. It doesn't even mention the Weld embedded container, so... I can only assume that it's the Arquillian extension we have that creates a full runtime environment by stuffing a bunch of dependencies into the archive. Which sounds wrong.

**Comment by xstefank** [comment]
it's wildfly container. I was able to manually override modules in downloaded wildfly to include latest smallrye health snapshot. I guess I can script it and run it after Wildfly is downloaded but I'm not sure if it's the right way to proceed.

**Comment by rsvoboda** [comment]
PR was merged 8 months ago, what changed since that time ?

> it's wildfly container. 

It's wildfly-servlet-dist to be precise. Previous comment could imply that it runs against full WildFly.

> I actually have no idea what Arquillian container we use for running the TCK

Agree it's a bit confusing. Also no arquillian.xml present => depending on ARQ defaults which are usually hard to findout (documentation challenge mentioned above)

**Comment by antoinesd** [comment]
PR was reverted to make sure that we'll be able to run the TCK on SmallRye
